[2023-10-22T18:16:05.125+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_dwh.hub_job_role_update manual__2023-10-22T18:16:00.387084+00:00 [queued]>
[2023-10-22T18:16:05.136+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_dwh.hub_job_role_update manual__2023-10-22T18:16:00.387084+00:00 [queued]>
[2023-10-22T18:16:05.136+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-22T18:16:05.146+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): hub_job_role_update> on 2023-10-22 18:16:00.387084+00:00
[2023-10-22T18:16:05.151+0000] {standard_task_runner.py:57} INFO - Started process 1984 to run task
[2023-10-22T18:16:05.155+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'update_dwh', 'hub_job_role_update', 'manual__2023-10-22T18:16:00.387084+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/update_dwh_dag.py', '--cfg-path', '/tmp/tmpx1bg5r5a']
[2023-10-22T18:16:05.157+0000] {standard_task_runner.py:85} INFO - Job 215: Subtask hub_job_role_update
[2023-10-22T18:16:05.200+0000] {task_command.py:416} INFO - Running <TaskInstance: update_dwh.hub_job_role_update manual__2023-10-22T18:16:00.387084+00:00 [running]> on host 1f8bb8a692af
[2023-10-22T18:16:05.285+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_dwh' AIRFLOW_CTX_TASK_ID='hub_job_role_update' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T18:16:00.387084+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T18:16:00.387084+00:00'
[2023-10-22T18:16:05.289+0000] {sql.py:274} INFO - Executing: 
INSERT INTO rdv.hub_job_role
SELECT DISTINCT
    MD5(p.jobrole),
    now(),
    'csv',
    p.department
FROM 
    staging.stg_table p
WHERE p.jobrole NOT IN (
    SELECT hub.job_role_name FROM rdv.hub_job_role hub
)
[2023-10-22T18:16:05.304+0000] {base.py:73} INFO - Using connection ID 'stg_conn' for task execution.
[2023-10-22T18:16:05.308+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/connection.py:374: AirflowProviderDeprecationWarning: The "schema" arg has been renamed to "database" as it contained the database name.Please use "database" to set the database name.
  return hook_class(**{hook.connection_id_attribute_name: self.conn_id}, **hook_params)

[2023-10-22T18:16:05.320+0000] {base.py:73} INFO - Using connection ID 'stg_conn' for task execution.
[2023-10-22T18:16:05.428+0000] {sql.py:418} INFO - Running statement: 
INSERT INTO rdv.hub_job_role
SELECT DISTINCT
    MD5(p.jobrole),
    now(),
    'csv',
    p.department
FROM 
    staging.stg_table p
WHERE p.jobrole NOT IN (
    SELECT hub.job_role_name FROM rdv.hub_job_role hub
), parameters: None
[2023-10-22T18:16:05.462+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "hub_job_role_pk"
DETAIL:  Key (job_role_hash_key)=(ae94be3cd532ce4a025884819eb08c98) already exists.

[2023-10-22T18:16:05.480+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=update_dwh, task_id=hub_job_role_update, execution_date=20231022T181600, start_date=20231022T181605, end_date=20231022T181605
[2023-10-22T18:16:05.507+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 215 for task hub_job_role_update (duplicate key value violates unique constraint "hub_job_role_pk"
DETAIL:  Key (job_role_hash_key)=(ae94be3cd532ce4a025884819eb08c98) already exists.
; 1984)
[2023-10-22T18:16:05.531+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T18:16:05.551+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
