[2023-11-17T13:26:45.776+0000] {processor.py:157} INFO - Started process (PID=2274) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:26:45.777+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:26:45.778+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:26:45.778+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:26:45.779+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:26:45.787+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.012 seconds
[2023-11-17T13:27:11.229+0000] {processor.py:157} INFO - Started process (PID=2313) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:27:11.230+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:27:11.232+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:27:11.232+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:27:11.237+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:27:11.235+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 2, in <module>
    from airflow.providers.apache.kafka.operators.consume import ConsumeFromTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-11-17T13:27:11.237+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:27:11.251+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.025 seconds
[2023-11-17T13:27:12.865+0000] {processor.py:157} INFO - Started process (PID=2332) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:27:12.866+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:27:12.869+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:27:12.868+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:27:12.874+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:27:12.873+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 2, in <module>
    from airflow.providers.apache.kafka.operators.consume import ConsumeFromTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-11-17T13:27:12.874+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:27:12.894+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.034 seconds
[2023-11-17T13:27:42.992+0000] {processor.py:157} INFO - Started process (PID=2390) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:27:42.995+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:27:42.997+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:27:42.997+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:27:43.001+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:27:43.000+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 2, in <module>
    from airflow.providers.apache.kafka.operators.consume import ConsumeFromTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-11-17T13:27:43.001+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:27:43.013+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T13:27:52.280+0000] {processor.py:157} INFO - Started process (PID=2394) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:27:52.282+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:27:52.285+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:27:52.285+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:27:52.288+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:27:52.287+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 5
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:27:52.288+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:27:52.300+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-17T13:28:22.370+0000] {processor.py:157} INFO - Started process (PID=2452) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:28:22.370+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:28:22.371+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:28:22.371+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:28:22.373+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:28:22.373+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 5
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:28:22.374+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:28:22.387+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-17T13:28:53.338+0000] {processor.py:157} INFO - Started process (PID=2506) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:28:53.341+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:28:53.343+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:28:53.343+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:28:53.345+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:28:53.344+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 5
    
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:28:53.345+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:28:53.357+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T13:29:02.559+0000] {processor.py:157} INFO - Started process (PID=2511) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:02.562+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:29:02.566+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:29:02.565+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:02.570+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:29:02.569+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 2, in <module>
    from airflow.providers.apache.kafka.operators.consume import ConsumeFromTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-11-17T13:29:02.570+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:02.583+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.027 seconds
[2023-11-17T13:29:08.815+0000] {processor.py:157} INFO - Started process (PID=2524) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:08.816+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:29:08.818+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:29:08.818+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:08.823+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:29:08.821+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 2, in <module>
    from airflow.providers.apache.kafka.operators.consume import ConsumeFromTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-11-17T13:29:08.823+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:08.845+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.032 seconds
[2023-11-17T13:29:12.112+0000] {processor.py:157} INFO - Started process (PID=2553) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:12.113+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:29:12.114+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:29:12.114+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:12.117+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:29:12.116+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 2, in <module>
    from airflow.providers.apache.kafka.operators.consume import ConsumeFromTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-11-17T13:29:12.117+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:12.129+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-17T13:29:18.723+0000] {processor.py:157} INFO - Started process (PID=2566) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:18.724+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:29:18.727+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:29:18.727+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:18.731+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:29:18.730+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 2, in <module>
    from airflow.providers.apache.kafka.operators.consume import ConsumeFromTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-11-17T13:29:18.731+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:18.742+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-17T13:29:22.762+0000] {processor.py:157} INFO - Started process (PID=2567) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:22.763+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:29:22.766+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:29:22.765+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:22.768+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:29:22.768+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 2, in <module>
    from airflow.providers.apache.kafka.operators.consume import ConsumeFromTopicOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2023-11-17T13:29:22.769+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:22.780+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T13:29:40.555+0000] {processor.py:157} INFO - Started process (PID=2593) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:40.556+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:29:40.559+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:29:40.559+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:40.562+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:29:40.561+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 12
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:29:40.563+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:29:40.576+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.026 seconds
[2023-11-17T13:30:10.635+0000] {processor.py:157} INFO - Started process (PID=2650) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:30:10.636+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:30:10.638+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:30:10.638+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:30:10.642+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:30:10.640+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 12
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:30:10.642+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:30:10.657+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.025 seconds
[2023-11-17T13:30:18.110+0000] {processor.py:157} INFO - Started process (PID=2683) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:30:18.111+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:30:18.113+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:30:18.112+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:30:18.116+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:30:18.115+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 16
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:30:18.116+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:30:18.132+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.024 seconds
[2023-11-17T13:30:30.390+0000] {processor.py:157} INFO - Started process (PID=2687) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:30:30.391+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:30:30.394+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:30:30.394+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:30:30.399+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:30:30.397+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:30:30.399+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:30:30.417+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.032 seconds
[2023-11-17T13:31:01.343+0000] {processor.py:157} INFO - Started process (PID=2744) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:31:01.344+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:31:01.346+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:31:01.346+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:31:01.350+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:31:01.348+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:31:01.350+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:31:01.361+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-17T13:31:32.197+0000] {processor.py:157} INFO - Started process (PID=2802) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:31:32.197+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:31:32.199+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:31:32.199+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:31:32.203+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:31:32.201+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:31:32.203+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:31:32.217+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T13:32:02.292+0000] {processor.py:157} INFO - Started process (PID=2859) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:32:02.293+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:32:02.296+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:32:02.296+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:32:02.301+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:32:02.299+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:32:02.301+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:32:02.313+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.026 seconds
[2023-11-17T13:32:32.483+0000] {processor.py:157} INFO - Started process (PID=2916) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:32:32.483+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:32:32.486+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:32:32.485+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:32:32.488+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:32:32.487+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:32:32.489+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:32:32.501+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T13:33:02.602+0000] {processor.py:157} INFO - Started process (PID=2974) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:33:02.603+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:33:02.607+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:33:02.606+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:33:02.611+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:33:02.610+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:33:02.612+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:33:02.631+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.034 seconds
[2023-11-17T13:33:32.734+0000] {processor.py:157} INFO - Started process (PID=3031) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:33:32.734+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:33:32.735+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:33:32.735+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:33:32.738+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:33:32.737+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:33:32.738+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:33:32.750+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-17T13:34:02.903+0000] {processor.py:157} INFO - Started process (PID=3088) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:34:02.904+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:34:02.908+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:34:02.907+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:34:02.912+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:34:02.911+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:34:02.912+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:34:02.926+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.028 seconds
[2023-11-17T13:34:32.955+0000] {processor.py:157} INFO - Started process (PID=3146) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:34:32.956+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:34:32.957+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:34:32.957+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:34:32.960+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:34:32.959+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:34:32.960+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:34:32.971+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.017 seconds
[2023-11-17T13:35:02.997+0000] {processor.py:157} INFO - Started process (PID=3201) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:35:02.998+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:35:03.000+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:35:02.999+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:35:03.003+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:35:03.002+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:35:03.003+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:35:03.018+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.024 seconds
[2023-11-17T13:35:33.933+0000] {processor.py:157} INFO - Started process (PID=3257) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:35:33.934+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:35:33.936+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:35:33.936+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:35:33.939+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:35:33.938+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:35:33.939+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:35:33.953+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.024 seconds
[2023-11-17T13:36:04.039+0000] {processor.py:157} INFO - Started process (PID=3315) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:36:04.040+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:36:04.042+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:36:04.042+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:36:04.046+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:36:04.045+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:36:04.047+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:36:04.070+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.034 seconds
[2023-11-17T13:36:34.130+0000] {processor.py:157} INFO - Started process (PID=3373) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:36:34.131+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:36:34.134+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:36:34.133+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:36:34.138+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:36:34.136+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:36:34.138+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:36:34.156+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.030 seconds
[2023-11-17T13:37:04.292+0000] {processor.py:157} INFO - Started process (PID=3430) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:37:04.293+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:37:04.295+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:37:04.295+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:37:04.299+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:37:04.298+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:37:04.299+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:37:04.325+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.034 seconds
[2023-11-17T13:37:34.529+0000] {processor.py:157} INFO - Started process (PID=3487) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:37:34.529+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:37:34.530+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:37:34.530+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:37:34.533+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:37:34.532+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:37:34.534+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:37:34.555+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.029 seconds
[2023-11-17T13:38:04.666+0000] {processor.py:157} INFO - Started process (PID=3544) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:38:04.666+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:38:04.668+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:38:04.668+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:38:04.671+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:38:04.670+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:38:04.672+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:38:04.694+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.031 seconds
[2023-11-17T13:38:34.851+0000] {processor.py:157} INFO - Started process (PID=3602) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:38:34.852+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:38:34.853+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:38:34.853+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:38:34.855+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:38:34.855+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:38:34.856+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:38:34.872+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-17T13:39:04.974+0000] {processor.py:157} INFO - Started process (PID=3659) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:39:04.975+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:39:04.977+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:39:04.976+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:39:04.980+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:39:04.979+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:39:04.980+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:39:05.002+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.030 seconds
[2023-11-17T13:39:35.393+0000] {processor.py:157} INFO - Started process (PID=3717) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:39:35.393+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:39:35.395+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:39:35.395+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:39:35.399+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:39:35.398+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:39:35.399+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:39:35.412+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T13:40:05.525+0000] {processor.py:157} INFO - Started process (PID=3774) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:40:05.526+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:40:05.528+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:40:05.528+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:40:05.534+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:40:05.533+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:40:05.534+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:40:05.560+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.038 seconds
[2023-11-17T13:40:35.806+0000] {processor.py:157} INFO - Started process (PID=3831) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:40:35.807+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:40:35.810+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:40:35.809+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:40:35.814+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:40:35.813+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:40:35.815+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:40:35.832+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.030 seconds
[2023-11-17T13:41:05.905+0000] {processor.py:157} INFO - Started process (PID=3888) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:41:05.906+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:41:05.909+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:41:05.908+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:41:05.915+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:41:05.913+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:41:05.915+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:41:05.937+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.036 seconds
[2023-11-17T13:41:36.069+0000] {processor.py:157} INFO - Started process (PID=3945) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:41:36.070+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:41:36.073+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:41:36.072+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:41:36.079+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:41:36.078+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:41:36.080+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:41:36.107+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.043 seconds
[2023-11-17T13:42:06.240+0000] {processor.py:157} INFO - Started process (PID=4002) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:42:06.241+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:42:06.244+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:42:06.243+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:42:06.250+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:42:06.248+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:42:06.250+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:42:06.276+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.039 seconds
[2023-11-17T13:42:36.767+0000] {processor.py:157} INFO - Started process (PID=4059) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:42:36.768+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:42:36.770+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:42:36.769+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:42:36.774+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:42:36.773+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:42:36.774+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:42:36.792+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.028 seconds
[2023-11-17T13:43:06.921+0000] {processor.py:157} INFO - Started process (PID=4116) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:43:06.921+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:43:06.924+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:43:06.923+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:43:06.928+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:43:06.926+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:43:06.928+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:43:06.948+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.029 seconds
[2023-11-17T13:43:37.511+0000] {processor.py:157} INFO - Started process (PID=4179) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:43:37.512+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:43:37.514+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:43:37.513+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:43:37.517+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:43:37.516+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:43:37.518+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:43:37.547+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.039 seconds
[2023-11-17T13:44:07.783+0000] {processor.py:157} INFO - Started process (PID=4237) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:44:07.784+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:44:07.786+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:44:07.785+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:44:07.790+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:44:07.789+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:44:07.791+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:44:07.813+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.033 seconds
[2023-11-17T13:44:38.340+0000] {processor.py:157} INFO - Started process (PID=4294) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:44:38.341+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:44:38.343+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:44:38.342+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:44:38.345+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:44:38.345+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:44:38.346+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:44:38.371+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.033 seconds
[2023-11-17T13:45:08.505+0000] {processor.py:157} INFO - Started process (PID=4351) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:45:08.506+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T13:45:08.510+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:45:08.509+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:45:08.515+0000] {logging_mixin.py:151} INFO - [2023-11-17T13:45:08.514+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T13:45:08.516+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T13:45:08.540+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.040 seconds
[2023-11-17T14:48:32.601+0000] {processor.py:157} INFO - Started process (PID=4401) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:48:32.613+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:48:32.617+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:48:32.616+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:48:32.648+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:48:32.642+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:48:32.650+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:48:32.718+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.135 seconds
[2023-11-17T14:49:03.377+0000] {processor.py:157} INFO - Started process (PID=4458) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:49:03.378+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:49:03.380+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:49:03.380+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:49:03.383+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:49:03.382+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:49:03.384+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:49:03.397+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T14:49:33.491+0000] {processor.py:157} INFO - Started process (PID=4515) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:49:33.494+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:49:33.495+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:49:33.495+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:49:33.497+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:49:33.496+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:49:33.497+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:49:33.511+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T14:50:03.693+0000] {processor.py:157} INFO - Started process (PID=4572) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:50:03.696+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:50:03.698+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:50:03.698+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:50:03.699+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:50:03.699+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:50:03.700+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:50:03.713+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T14:50:33.808+0000] {processor.py:157} INFO - Started process (PID=4629) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:50:33.811+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:50:33.813+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:50:33.813+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:50:33.816+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:50:33.815+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:50:33.816+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:50:33.833+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.027 seconds
[2023-11-17T14:51:03.887+0000] {processor.py:157} INFO - Started process (PID=4686) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:51:03.890+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:51:03.892+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:51:03.892+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:51:03.893+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:51:03.893+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:51:03.894+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:51:03.908+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T14:51:33.981+0000] {processor.py:157} INFO - Started process (PID=4743) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:51:33.984+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:51:33.985+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:51:33.985+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:51:33.987+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:51:33.987+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:51:33.987+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:51:34.000+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T14:52:04.048+0000] {processor.py:157} INFO - Started process (PID=4801) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:52:04.049+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:52:04.050+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:52:04.050+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:52:04.052+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:52:04.052+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:52:04.052+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:52:04.063+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.017 seconds
[2023-11-17T14:52:34.203+0000] {processor.py:157} INFO - Started process (PID=4858) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:52:34.205+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:52:34.207+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:52:34.207+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:52:34.209+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:52:34.209+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:52:34.210+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:52:34.223+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.024 seconds
[2023-11-17T14:53:04.286+0000] {processor.py:157} INFO - Started process (PID=4915) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:53:04.288+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:53:04.290+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:53:04.289+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:53:04.292+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:53:04.291+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:53:04.292+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:53:04.305+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T14:53:34.358+0000] {processor.py:157} INFO - Started process (PID=4972) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:53:34.360+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:53:34.362+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:53:34.361+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:53:34.363+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:53:34.363+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:53:34.364+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:53:34.376+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T14:54:04.532+0000] {processor.py:157} INFO - Started process (PID=5029) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:54:04.534+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:54:04.536+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:54:04.536+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:54:04.538+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:54:04.537+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:54:04.538+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:54:04.551+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T14:54:34.616+0000] {processor.py:157} INFO - Started process (PID=5086) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:54:34.619+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:54:34.620+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:54:34.620+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:54:34.622+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:54:34.621+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:54:34.622+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:54:34.636+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T14:55:05.384+0000] {processor.py:157} INFO - Started process (PID=5143) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:55:05.386+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:55:05.388+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:55:05.388+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:55:05.390+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:55:05.389+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:55:05.390+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:55:05.403+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T14:55:36.103+0000] {processor.py:157} INFO - Started process (PID=5201) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:55:36.106+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:55:36.107+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:55:36.107+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:55:36.109+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:55:36.108+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:55:36.109+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:55:36.121+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-17T14:56:06.903+0000] {processor.py:157} INFO - Started process (PID=5258) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:56:06.904+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:56:06.905+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:56:06.905+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:56:06.907+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:56:06.906+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:56:06.907+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:56:06.920+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-17T14:56:37.602+0000] {processor.py:157} INFO - Started process (PID=5315) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:56:37.604+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:56:37.606+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:56:37.606+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:56:37.609+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:56:37.608+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:56:37.609+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:56:37.624+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.025 seconds
[2023-11-17T14:57:08.436+0000] {processor.py:157} INFO - Started process (PID=5372) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:57:08.437+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:57:08.438+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:57:08.438+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:57:08.441+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:57:08.440+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:57:08.441+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:57:08.455+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T14:57:39.187+0000] {processor.py:157} INFO - Started process (PID=5429) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:57:39.190+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:57:39.192+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:57:39.192+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:57:39.194+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:57:39.193+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:57:39.194+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:57:39.215+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.032 seconds
[2023-11-17T14:58:10.010+0000] {processor.py:157} INFO - Started process (PID=5493) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:58:10.013+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:58:10.015+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:58:10.015+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:58:10.017+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:58:10.016+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:58:10.017+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:58:10.029+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-17T14:58:40.764+0000] {processor.py:157} INFO - Started process (PID=5550) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:58:40.766+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:58:40.769+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:58:40.768+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:58:40.770+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:58:40.770+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:58:40.770+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:58:40.784+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-17T14:59:11.558+0000] {processor.py:157} INFO - Started process (PID=5607) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:59:11.560+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:59:11.562+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:59:11.562+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:59:11.563+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:59:11.563+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:59:11.564+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:59:11.577+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T14:59:41.670+0000] {processor.py:157} INFO - Started process (PID=5664) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:59:41.672+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T14:59:41.674+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:59:41.674+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:59:41.676+0000] {logging_mixin.py:151} INFO - [2023-11-17T14:59:41.675+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T14:59:41.676+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T14:59:41.690+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T15:00:11.810+0000] {processor.py:157} INFO - Started process (PID=5722) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:00:11.810+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:00:11.811+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:00:11.811+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:00:11.813+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:00:11.813+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:00:11.813+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:00:11.826+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-17T15:00:42.011+0000] {processor.py:157} INFO - Started process (PID=5780) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:00:42.014+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:00:42.015+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:00:42.015+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:00:42.017+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:00:42.016+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:00:42.017+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:00:42.030+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T15:01:12.105+0000] {processor.py:157} INFO - Started process (PID=5837) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:01:12.106+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:01:12.107+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:01:12.107+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:01:12.109+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:01:12.108+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:01:12.109+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:01:12.121+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.018 seconds
[2023-11-17T15:01:42.297+0000] {processor.py:157} INFO - Started process (PID=5894) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:01:42.300+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:01:42.301+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:01:42.301+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:01:42.303+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:01:42.303+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:01:42.303+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:01:42.317+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T15:02:12.994+0000] {processor.py:157} INFO - Started process (PID=5951) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:02:12.996+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:02:12.998+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:02:12.998+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:02:13.000+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:02:13.000+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:02:13.000+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:02:13.013+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T15:02:43.109+0000] {processor.py:157} INFO - Started process (PID=6008) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:02:43.112+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:02:43.114+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:02:43.113+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:02:43.115+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:02:43.115+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:02:43.116+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:02:43.130+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-17T15:03:13.253+0000] {processor.py:157} INFO - Started process (PID=6065) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:03:13.256+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:03:13.258+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:03:13.258+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:03:13.259+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:03:13.259+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:03:13.260+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:03:13.271+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-17T15:03:43.447+0000] {processor.py:157} INFO - Started process (PID=6123) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:03:43.449+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:03:43.451+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:03:43.451+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:03:43.453+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:03:43.452+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:03:43.453+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:03:43.466+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T15:04:13.526+0000] {processor.py:157} INFO - Started process (PID=6180) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:04:13.529+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:04:13.530+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:04:13.530+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:04:13.532+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:04:13.532+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:04:13.533+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:04:13.545+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T15:14:16.277+0000] {processor.py:157} INFO - Started process (PID=6228) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:14:16.278+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:14:16.280+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:14:16.279+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:14:16.281+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:14:16.281+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:14:16.282+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:14:16.298+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.024 seconds
[2023-11-17T15:14:46.772+0000] {processor.py:157} INFO - Started process (PID=6285) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:14:46.775+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:14:46.776+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:14:46.776+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:14:46.778+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:14:46.778+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:14:46.779+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:14:46.792+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.024 seconds
[2023-11-17T15:15:16.889+0000] {processor.py:157} INFO - Started process (PID=6342) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:15:16.892+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:15:16.894+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:15:16.893+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:15:16.896+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:15:16.895+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:15:16.896+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:15:16.913+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.026 seconds
[2023-11-17T15:15:47.013+0000] {processor.py:157} INFO - Started process (PID=6399) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:15:47.016+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:15:47.017+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:15:47.017+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:15:47.019+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:15:47.018+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:15:47.019+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:15:47.032+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T15:16:17.172+0000] {processor.py:157} INFO - Started process (PID=6456) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:16:17.175+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:16:17.176+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:16:17.176+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:16:17.178+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:16:17.178+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:16:17.178+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:16:17.191+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T15:16:47.326+0000] {processor.py:157} INFO - Started process (PID=6512) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:16:47.326+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:16:47.328+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:16:47.328+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:16:47.330+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:16:47.329+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:16:47.330+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:16:47.341+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.018 seconds
[2023-11-17T15:17:17.464+0000] {processor.py:157} INFO - Started process (PID=6570) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:17:17.465+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:17:17.467+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:17:17.467+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:17:17.469+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:17:17.468+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:17:17.469+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:17:17.481+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.018 seconds
[2023-11-17T15:17:47.586+0000] {processor.py:157} INFO - Started process (PID=6627) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:17:47.589+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:17:47.590+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:17:47.590+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:17:47.592+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:17:47.592+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:17:47.592+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:17:47.605+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T15:18:17.710+0000] {processor.py:157} INFO - Started process (PID=6684) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:18:17.711+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:18:17.713+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:18:17.712+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:18:17.714+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:18:17.714+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:18:17.714+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:18:17.727+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.018 seconds
[2023-11-17T15:18:47.837+0000] {processor.py:157} INFO - Started process (PID=6741) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:18:47.839+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:18:47.841+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:18:47.841+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:18:47.843+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:18:47.842+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:18:47.843+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:18:47.856+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T15:19:17.954+0000] {processor.py:157} INFO - Started process (PID=6799) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:19:17.955+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:19:17.957+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:19:17.957+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:19:17.959+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:19:17.958+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:19:17.959+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:19:17.972+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T15:19:48.065+0000] {processor.py:157} INFO - Started process (PID=6856) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:19:48.067+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:19:48.069+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:19:48.069+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:19:48.071+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:19:48.070+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:19:48.071+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:19:48.085+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T15:20:18.119+0000] {processor.py:157} INFO - Started process (PID=6913) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:20:18.122+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:20:18.123+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:20:18.123+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:20:18.125+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:20:18.124+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:20:18.125+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:20:18.138+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-17T15:20:48.249+0000] {processor.py:157} INFO - Started process (PID=6970) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:20:48.251+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:20:48.253+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:20:48.253+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:20:48.255+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:20:48.254+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:20:48.255+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:20:48.267+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-17T15:21:18.302+0000] {processor.py:157} INFO - Started process (PID=7027) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:21:18.302+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:21:18.303+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:21:18.303+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:21:18.305+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:21:18.305+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:21:18.305+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:21:18.319+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-17T15:21:48.468+0000] {processor.py:157} INFO - Started process (PID=7084) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:21:48.470+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:21:48.472+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:21:48.471+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:21:48.474+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:21:48.473+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:21:48.474+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:21:48.486+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T15:22:18.568+0000] {processor.py:157} INFO - Started process (PID=7142) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:22:18.568+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:22:18.570+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:22:18.570+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:22:18.573+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:22:18.572+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:22:18.573+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:22:18.586+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-17T15:22:48.772+0000] {processor.py:157} INFO - Started process (PID=7199) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:22:48.775+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:22:48.776+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:22:48.776+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:22:48.778+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:22:48.777+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:22:48.778+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:22:48.791+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T15:23:18.823+0000] {processor.py:157} INFO - Started process (PID=7256) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:23:18.825+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:23:18.827+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:23:18.826+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:23:18.828+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:23:18.828+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:23:18.828+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:23:18.840+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T15:23:48.869+0000] {processor.py:157} INFO - Started process (PID=7313) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:23:48.870+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:23:48.872+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:23:48.872+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:23:48.874+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:23:48.873+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:23:48.874+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:23:48.887+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-17T15:24:19.724+0000] {processor.py:157} INFO - Started process (PID=7370) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:24:19.727+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:24:19.728+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:24:19.728+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:24:19.730+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:24:19.730+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:24:19.730+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:24:19.743+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T15:24:50.467+0000] {processor.py:157} INFO - Started process (PID=7427) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:24:50.470+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:24:50.472+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:24:50.472+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:24:50.474+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:24:50.473+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:24:50.474+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:24:50.487+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.025 seconds
[2023-11-17T15:25:20.503+0000] {processor.py:157} INFO - Started process (PID=7484) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:25:20.505+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:25:20.508+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:25:20.508+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:25:20.510+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:25:20.510+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:25:20.511+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:25:20.525+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.024 seconds
[2023-11-17T15:25:50.562+0000] {processor.py:157} INFO - Started process (PID=7541) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:25:50.562+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:25:50.564+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:25:50.564+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:25:50.566+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:25:50.565+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:25:50.566+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:25:50.578+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-17T15:26:20.649+0000] {processor.py:157} INFO - Started process (PID=7599) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:26:20.649+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:26:20.651+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:26:20.651+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:26:20.653+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:26:20.652+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:26:20.653+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:26:20.665+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-17T15:26:50.787+0000] {processor.py:157} INFO - Started process (PID=7656) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:26:50.788+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:26:50.790+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:26:50.789+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:26:50.791+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:26:50.791+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:26:50.792+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:26:50.804+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-17T15:27:20.883+0000] {processor.py:157} INFO - Started process (PID=7713) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:27:20.885+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:27:20.887+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:27:20.887+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:27:20.889+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:27:20.889+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:27:20.889+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:27:20.902+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T15:27:50.930+0000] {processor.py:157} INFO - Started process (PID=7770) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:27:50.931+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:27:50.933+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:27:50.933+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:27:50.935+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:27:50.935+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:27:50.935+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:27:50.947+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-17T15:28:20.960+0000] {processor.py:157} INFO - Started process (PID=7827) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:28:20.961+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:28:20.962+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:28:20.962+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:28:20.964+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:28:20.964+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:28:20.964+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:28:20.977+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-17T15:28:51.040+0000] {processor.py:157} INFO - Started process (PID=7884) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:28:51.042+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:28:51.044+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:28:51.043+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:28:51.046+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:28:51.045+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:28:51.046+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:28:51.058+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T15:29:21.153+0000] {processor.py:157} INFO - Started process (PID=7941) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:29:21.155+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:29:21.157+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:29:21.156+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:29:21.158+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:29:21.158+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:29:21.158+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:29:21.172+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.022 seconds
[2023-11-17T15:29:51.197+0000] {processor.py:157} INFO - Started process (PID=7998) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:29:51.200+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:29:51.201+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:29:51.201+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:29:51.203+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:29:51.202+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:29:51.203+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:29:51.216+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T15:30:21.402+0000] {processor.py:157} INFO - Started process (PID=8056) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:30:21.402+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:30:21.403+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:30:21.403+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:30:21.405+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:30:21.405+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:30:21.405+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:30:21.418+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.018 seconds
[2023-11-17T15:30:51.565+0000] {processor.py:157} INFO - Started process (PID=8113) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:30:51.567+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:30:51.569+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:30:51.568+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:30:51.570+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:30:51.570+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:30:51.570+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:30:51.583+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-17T15:31:21.750+0000] {processor.py:157} INFO - Started process (PID=8170) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:31:21.750+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:31:21.752+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:31:21.751+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:31:21.754+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:31:21.753+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:31:21.754+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:31:21.765+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.018 seconds
[2023-11-17T15:31:52.748+0000] {processor.py:157} INFO - Started process (PID=8227) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:31:52.750+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:31:52.752+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:31:52.751+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:31:52.753+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:31:52.753+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:31:52.754+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:31:52.766+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T15:32:22.812+0000] {processor.py:157} INFO - Started process (PID=8284) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:32:22.813+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:32:22.814+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:32:22.814+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:32:22.816+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:32:22.815+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:32:22.816+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:32:22.829+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.019 seconds
[2023-11-17T15:32:53.620+0000] {processor.py:157} INFO - Started process (PID=8341) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:32:53.622+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:32:53.624+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:32:53.624+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:32:53.626+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:32:53.625+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:32:53.626+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:32:53.639+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
[2023-11-17T15:33:23.713+0000] {processor.py:157} INFO - Started process (PID=8399) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:33:23.716+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:33:23.717+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:33:23.717+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:33:23.719+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:33:23.719+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:33:23.720+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:33:23.732+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.023 seconds
[2023-11-17T15:33:53.761+0000] {processor.py:157} INFO - Started process (PID=8456) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:33:53.763+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:33:53.765+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:33:53.765+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:33:53.768+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:33:53.767+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:33:53.768+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:33:53.781+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.024 seconds
[2023-11-17T15:34:24.465+0000] {processor.py:157} INFO - Started process (PID=8513) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:34:24.465+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:34:24.467+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:34:24.467+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:34:24.469+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:34:24.468+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:34:24.469+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:34:24.481+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.018 seconds
[2023-11-17T15:34:55.197+0000] {processor.py:157} INFO - Started process (PID=8570) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:34:55.199+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:34:55.201+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:34:55.201+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:34:55.203+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:34:55.202+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:34:55.203+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:34:55.215+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-17T15:35:25.875+0000] {processor.py:157} INFO - Started process (PID=8627) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:35:25.877+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T15:35:25.878+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:35:25.878+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:35:25.880+0000] {logging_mixin.py:151} INFO - [2023-11-17T15:35:25.880+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T15:35:25.880+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T15:35:25.892+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.020 seconds
[2023-11-17T16:50:07.442+0000] {processor.py:157} INFO - Started process (PID=8652) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T16:50:07.444+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T16:50:07.445+0000] {logging_mixin.py:151} INFO - [2023-11-17T16:50:07.445+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T16:50:07.448+0000] {logging_mixin.py:151} INFO - [2023-11-17T16:50:07.447+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T16:50:07.448+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T16:50:07.464+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.024 seconds
[2023-11-17T16:50:37.757+0000] {processor.py:157} INFO - Started process (PID=8709) to work on /opt/airflow/dags/update_actions_dag.py
[2023-11-17T16:50:37.758+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/update_actions_dag.py for tasks to queue
[2023-11-17T16:50:37.759+0000] {logging_mixin.py:151} INFO - [2023-11-17T16:50:37.759+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T16:50:37.762+0000] {logging_mixin.py:151} INFO - [2023-11-17T16:50:37.761+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/update_actions_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/update_actions_dag.py", line 17
    )
    ^
SyntaxError: unexpected EOF while parsing
[2023-11-17T16:50:37.762+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/update_actions_dag.py
[2023-11-17T16:50:37.776+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/update_actions_dag.py took 0.021 seconds
