[2023-10-22T17:45:56.213+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_dwh.hub_department_update manual__2023-10-22T17:45:51.060492+00:00 [queued]>
[2023-10-22T17:45:56.223+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_dwh.hub_department_update manual__2023-10-22T17:45:51.060492+00:00 [queued]>
[2023-10-22T17:45:56.224+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-22T17:45:56.239+0000] {taskinstance.py:1382} INFO - Executing <Task(SQLExecuteQueryOperator): hub_department_update> on 2023-10-22 17:45:51.060492+00:00
[2023-10-22T17:45:56.248+0000] {standard_task_runner.py:57} INFO - Started process 1483 to run task
[2023-10-22T17:45:56.252+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'update_dwh', 'hub_department_update', 'manual__2023-10-22T17:45:51.060492+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/update_dwh_dag.py', '--cfg-path', '/tmp/tmpn707uq3d']
[2023-10-22T17:45:56.255+0000] {standard_task_runner.py:85} INFO - Job 199: Subtask hub_department_update
[2023-10-22T17:45:56.307+0000] {task_command.py:416} INFO - Running <TaskInstance: update_dwh.hub_department_update manual__2023-10-22T17:45:51.060492+00:00 [running]> on host 1f8bb8a692af
[2023-10-22T17:45:56.399+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_dwh' AIRFLOW_CTX_TASK_ID='hub_department_update' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T17:45:51.060492+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T17:45:51.060492+00:00'
[2023-10-22T17:45:56.400+0000] {sql.py:274} INFO - Executing: 
INSERT INTO rdv.hub_department
SELECT DISTINCT
    MD5(p.department),
    now(),
    'csv',
    p.department
FROM 
    staging.stg_table p
WHERE p.department NOT IN (
    SELECT hub.department_name FROM rdv.hub_department hub
)
[2023-10-22T17:45:56.401+0000] {connection.py:471} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 466, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/secrets/base_secrets.py", line 96, in get_connection
    value = self.get_conn_value(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/secrets/environment_variables.py", line 51, in get_conn_value
    return os.environ.get(CONN_ENV_PREFIX + conn_id.upper())
AttributeError: 'NoneType' object has no attribute 'upper'
[2023-10-22T17:45:56.421+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `None` isn't defined
[2023-10-22T17:45:56.426+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=update_dwh, task_id=hub_department_update, execution_date=20231022T174551, start_date=20231022T174556, end_date=20231022T174556
[2023-10-22T17:45:56.438+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 199 for task hub_department_update (The conn_id `None` isn't defined; 1483)
[2023-10-22T17:45:56.466+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T17:45:56.483+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
